name: 'prow-github-actions'
description: 'Prow inspired github CI/CD actions'
author: 'John McBride'
inputs:
  github-token:
    description: "Github token"
    required: true
  prow-command:
    description: "Comment keyword/command to look for"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
