name: Merge on lgtm label
on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - uses: ./
        with:
          jobs: lgtm
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          merge-method: squash
